name: Build Docker Image
run-name: Running build image

on:
  push:
    tags:
      - "v1.*"

jobs:
  build-app:
    name: Build Go App
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.upload-bin.outputs.artifact-id }}

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.4"

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download dependencies
        run: go mod tidy

      - name: Build Linux
        run: go build -o app-linux main.go

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o app-windows.exe main.go

      - name: Build macOS
        run: GOOS=darwin GOARCH=arm64 go build -o app-darwin main.go

      - name: Build Release
        run: go build -o app main.go

      - name: Upload Artifact
        id: upload-bin
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: app

  release-app:
        name: "Release builded app"
        needs: build-app
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v5
              with:
                artifact-ids: ${{needs.build-app.outputs.output1}}
            - name: Compress artifact
              run: zip -r app.zip ./*
            - name: Release
              uses: softprops/action-gh-release@v3
              with:
                files:
                    app.zip
    
  build-image:
        runs-on: ubuntu-latest
        needs: release-app
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: login to docker
              run: echo -n ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{github.actor}} --password-stdin
            - name: Build image
              run: docker build -t ghcr.io/${{github.repository}}:pra .
            - name: push to ghcr.io
              run: docker push ghcr.io/${{github.repository}}:pra